kind: Deployment
apiVersion: apps/v1
metadata:
   name: my-baseline-deployment
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: my-baseline-app
   template:
      metadata:
        labels:
          app: my-baseline-app
      spec:
       containers:
        - name: container-k
          image: karthi22dock/webapp_proj:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80