kind: Service                             
apiVersion: v1
metadata:
  name: Baseline
  labels:
    app: Baseline
spec:
  ports:
    - port: 8080                              
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: Baseline                    
  type: LoadBalancer                