kind: Service                             
apiVersion: v1
metadata:
  name: my-baseline-deployment
  labels:
    app: my-baseline-app
spec:
  ports:
    - port: 8080                              
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: my-baseline-app                    
  type: LoadBalancer                